apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jenkins-eyecatcher
  janus-idp.io/tekton: jenkins-eyecatcher
  backstage.io/kubernetes-id: jenkins-eyecatcher
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jenkins-eyecatcher
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
