apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: jenkins-eyecatcher
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jenkins-eyecatcher 
  name: jenkins-eyecatcher
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jenkins-eyecatcher
    weight: 100 
