apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jenkins-eyecatcher
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jenkins-eyecatcher 
  name: jenkins-eyecatcher
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jenkins-eyecatcher 
